# arpspoof
# Autogenerated from man page /usr/lib/jvm/default/man/man8/arpspoof.8.gz
complete -c arpspoof -s i -d 'Specify the interface to use'
complete -c arpspoof -s c -d 'Specify which hardware address t use when restoring the arp configuration; wh…'
complete -c arpspoof -s t -d 'Specify a particular host to ARP poison (if not specified, all hosts on the L…'
complete -c arpspoof -s r -d 'Poison both hosts (host and target) to capture traffic in both directions'

