# at
# Autogenerated from man page /usr/lib/jvm/default/man/man1/at.1p.gz
complete -c at -o ffile --description 'Specify the pathname of a file to be used as the source of the at-job, instea…'
complete -c at -s l --description '(The letter ell.'
complete -c at -s m --description 'Send mail to the invoking user after the at-job has run, announcing its compl…'
complete -c at -o qqueuename --description 'br Specify in which queue to schedule a job for submission.'
complete -c at -s r --description 'Remove the jobs with the specified R at_job_id operands that were previously …'
complete -c at -s f --description 'Specify the pathname of a file to be used as the source of the at-job, instea…'
complete -c at -s q --description '.'
complete -c at -s t --description 'time_arg or timespec arguments, the results are unspecified.'
complete -c at -s u --description 'user option has allowed those with appropriate privileges to access the work …'

