# cadaver
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cadaver.1.gz
complete -c cadaver -s t -l tolerant -d 'Allow cd/open into non-WebDAV enabled collection; use if the server or proxy …'
complete -c cadaver -s r -l rcfile -d 'Use this rcfile rather than the default of   ~/. cadaverrc'
complete -c cadaver -s p -l proxy -d 'Connect using the proxy host "host" and optional proxy port "port"'
complete -c cadaver -s V -l version -d 'Display version information and exit'
complete -c cadaver -s h -l help -d 'Display this help message and exit'

