# cgps
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cgps.1.gz
complete -c cgps -s '?' -s h -l help --description '.'
complete -c cgps -s V -l version --description '.'
complete -c cgps -s D -l debug --description '.'
complete -c cgps -s l -l llfmt --description '.'
complete -c cgps -s s -l silent --description '.'
complete -c cgps -s m -l magtrack --description '.'
complete -c cgps -s u -l units --description '.'
complete -c cgps -s d -l kmldir --description '.'
complete -c cgps -l device --description '.'
complete -c cgps -l host --description '.'
complete -c cgps -s i -l initialize --description '.'
complete -c cgps -l port --description '.'
complete -c cgps -l sleep --description '.'

