# cluster
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cluster.1.gz
complete -c cluster -s C --description 'specifies a targeted number of clusters that should be generated.'
complete -c cluster -s c --description 'specifies clustering method.'
complete -c cluster -s o --description 'Specifies that output should go into the file outfile.'
complete -c cluster -s v --description 'Verbose mode.'
complete -c cluster -s '?' --description 'Prints the usage and exits.  EXAMPLES.'

