# compress
# Autogenerated from man page /usr/lib/jvm/default/man/man1/compress.1p.gz
complete -c compress -o bbits --description 'Specify the maximum number of bits to use in a code.'
complete -c compress -s c --description 'Cause R compress to write to the standard output; the input file is not chang…'
complete -c compress -s f --description 'Force compression of R file , even if it does not actually reduce the size of…'
complete -c compress -s b --description 'Specify the maximum number of bits to use in a code.'
complete -c compress -s v --description 'Write the percentage reduction of each file to standard error.'

