# csplit
# Autogenerated from man page /usr/lib/jvm/default/man/man1/csplit.1p.gz
complete -c csplit -o fprefix --description 'Name the created files R prefix \\c  00 , R prefix \\c  01 , . \\|. \\|.'
complete -c csplit -o nnumber --description 'Use R number decimal digits to form filenames for the file pieces.'
complete -c csplit -s a --description 'flag to use the alphabetic filename generation used by the historical split u…'

