# cut
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cut.1p.gz
complete -c cut -o blist --description 'Cut based on a R list of bytes.'
complete -c cut -o clist --description 'Cut based on a R list of characters.  Each selected character shall be output.'
complete -c cut -o ddelim --description 'Set the field delimiter to the character R delim .  The default is the <tab>.'
complete -c cut -o flist --description 'Cut based on a R list of fields, assumed to be separated in the file by a del…'
complete -c cut -s 5 --description 'Equivalent to 1,2,3,4,5,10.  3- 8 Equivalent to third to last, inclusive.'
complete -c cut -s o --description 'Preserve the selected field order.'

