# cxref
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cxref.1p.gz
complete -c cxref -s c --description 'Write a combined cross-reference of all input files.'
complete -c cxref -s s --description 'Operate silently; do not print input filenames.'
complete -c cxref -o ofile --description 'Direct output to named R file .'
complete -c cxref -o wnum --description 'Format output no wider than R num (decimal) columns.'
complete -c cxref -s D --description 'Equivalent to R c99 .'
complete -c cxref -s I --description 'Equivalent to R c99 .'
complete -c cxref -s U --description 'options (which are identical to their interpretation by c99 ) is significant.'
complete -c cxref -s o --description 'Direct output to named file .'
complete -c cxref -s w --description 'Format output no wider than num (decimal) columns.'

