# daxctl-create-device
# Autogenerated from man page /usr/lib/jvm/default/man/man1/daxctl-create-device.1.gz
complete -c daxctl-create-device -s r -l region --description '.'
complete -c daxctl-create-device -s s -l size --description '.'
complete -c daxctl-create-device -s a -l align --description '.'
complete -c daxctl-create-device -l input --description '.'
complete -c daxctl-create-device -s u -l human --description '.'
complete -c daxctl-create-device -s v -l verbose --description '.'

