# daxctl-destroy-device
# Autogenerated from man page /usr/lib/jvm/default/man/man1/daxctl-destroy-device.1.gz
complete -c daxctl-destroy-device -s r -l region --description '.'
complete -c daxctl-destroy-device -s u -l human --description '.'
complete -c daxctl-destroy-device -s v -l verbose --description '.'

