# daxctl-disable-device
# Autogenerated from man page /usr/lib/jvm/default/man/man1/daxctl-disable-device.1.gz
complete -c daxctl-disable-device -s r -l region --description '.'
complete -c daxctl-disable-device -s u -l human --description '.'
complete -c daxctl-disable-device -s v -l verbose --description '.'

