# daxctl-enable-device
# Autogenerated from man page /usr/lib/jvm/default/man/man1/daxctl-enable-device.1.gz
complete -c daxctl-enable-device -s r -l region --description '.'
complete -c daxctl-enable-device -s u -l human --description '.'
complete -c daxctl-enable-device -s v -l verbose --description '.'

