# dc3dd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dc3dd.1.gz
complete -c dc3dd -l help -d 'display this help and exit'
complete -c dc3dd -l version -d 'output version information and exit'
complete -c dc3dd -l ---- -d usage:
complete -c dc3dd -l ------------ -d 'basic options:'
complete -c dc3dd -o DDEFAULT_OUTPUT_FILE_SIZE -d 'value in BYTES'
complete -c dc3dd -o DDEFAULT_HASH_SHA256 -o DDEFAULT_HASH_SHA512
complete -c dc3dd -l --------------- -d 'advanced options:'
complete -c dc3dd -l ----------- -d 'help options:'
complete -c dc3dd -l flags -d 'display compile-time flags and exit'

