# dcb
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dcb.8.gz
complete -c dcb -s n -l netns --description 'switches  dcb to the specified network namespace R NETNS .'
complete -c dcb -s V -l Version --description 'Print the version of the  dcb utility and exit.'
complete -c dcb -s b -l batch --description 'Read commands from provided file or standard input and invoke them.'
complete -c dcb -s f -l force --description 'Don\'t terminate dcb on errors in batch mode.'
complete -c dcb -s i -l iec --description 'When showing rates, use ISO/IEC 1024-based prefixes (Ki, Mi, Bi) instead of t…'
complete -c dcb -s j -l json --description 'Generate JSON output.'
complete -c dcb -s p -l pretty --description 'When combined with -j generate a pretty JSON output.'
complete -c dcb -s s -l statistics --description 'If the object in question contains any statistical counters, shown them as pa…'

