# dcfldd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dcfldd.1.gz
complete -c dcfldd -l help -d 'Display a help page and exit'
complete -c dcfldd -l version -d 'Output version information and exit'

