# ddns-confgen
# Autogenerated from man page /usr/lib/jvm/default/man/man8/ddns-confgen.8.gz
complete -c ddns-confgen -s a -d 'Specifies the algorithm to use for the TSIG key'
complete -c ddns-confgen -s h -d 'Prints a short summary of options and arguments'
complete -c ddns-confgen -s k -d 'Specifies the key name of the DDNS authentication key'
complete -c ddns-confgen -s q -d '(ddns-confgen only'
complete -c ddns-confgen -s s -d '(ddns-confgen only'
complete -c ddns-confgen -s z -d '(ddns-confgen only'

