# delta
# Autogenerated from man page /usr/lib/jvm/default/man/man1/delta.1p.gz
complete -c delta -o rSID --description 'Uniquely identify which delta is to be made to the SCCS file.'
complete -c delta -s s --description 'Suppress the report to standard output of the activity associated with each R…'
complete -c delta -s n --description 'Specify retention of the edited R g-file (normally removed at completion of d…'
complete -c delta -o glist --description 'Specify a R list (see R "get" for the definition of R list ) of deltas that s…'
complete -c delta -o mmrlist --description 'Specify a modification request (MR) number that the application shall supply …'
complete -c delta -s y --description 'Describe the reason for making the delta.'
complete -c delta -s r --description 'Uniquely identify which delta is to be made to the SCCS file.'
complete -c delta -s e --description 'on the same SCCS file were done by the same person (login name).'
complete -c delta -s g --description 'Specify a list (see get for the definition of list ) of deltas that shall be …'
complete -c delta -s m --description 'Specify a modification request (MR) number that the application shall supply …'
complete -c delta -s p --description 'Write (to standard output) the SCCS file differences before and after the del…'

