# diff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/diff.1p.gz
complete -c diff -o Cn --description 'Produce output in a form that provides R n lines of copied context (where R n…'
complete -c diff -s f --description 'Produce output in an alternative form, similar in format to  -e , but not int…'
complete -c diff -l - --description '> Tue Jun 19 21:41:39 PDT 1990 RATIONALE The.'
complete -c diff -s h --description 'option was omitted because it was insufficiently specified and does not add t…'

