# dnssec-cds
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnssec-cds.8.gz
complete -c dnssec-cds -s a -d 'Specify a digest algorithm to use when converting CDNSKEY records to DS recor…'
complete -c dnssec-cds -s c -d 'Specifies the DNS class of the zones'
complete -c dnssec-cds -s D -d 'Generate DS records from CDNSKEY records if both CDS and CDNSKEY records are …'
complete -c dnssec-cds -s d -d 'Location of the parent DS records'
complete -c dnssec-cds -s f -d 'File containing the child\\(aqs CDS and/or CDNSKEY records, plus its DNSKEY re…'
complete -c dnssec-cds -o iextension -d 'Update the dsset- file in place, instead of writing DS records to the standar…'
complete -c dnssec-cds -s s -d 'Specify the date and time after which RRSIG records become acceptable'
complete -c dnssec-cds -s T -d 'Specifies a TTL to be used for new DS records'
complete -c dnssec-cds -s u -d 'Write an nsupdate script to the standard output, instead of printing the new …'
complete -c dnssec-cds -s V -d 'Print version information'
complete -c dnssec-cds -s v -d 'Sets the debugging level'

