# dnssec-revoke
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnssec-revoke.8.gz
complete -c dnssec-revoke -s h -d 'Emit usage message and exit'
complete -c dnssec-revoke -s K -d 'Sets the directory in which the key files are to reside'
complete -c dnssec-revoke -s r -d 'After writing the new keyset files remove the original keyset files'
complete -c dnssec-revoke -s v -d 'Sets the debugging level'
complete -c dnssec-revoke -s V -d 'Prints version information'
complete -c dnssec-revoke -s E -d 'Specifies the cryptographic hardware to use, when applicable'
complete -c dnssec-revoke -s f -d 'Force overwrite: Causes dnssec-revoke to write the new key pair even if a fil…'
complete -c dnssec-revoke -s R -d 'Print the key tag of the key with the REVOKE bit set but do not revoke the key'

