# dnssec-verify
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnssec-verify.8.gz
complete -c dnssec-verify -s c -d 'Specifies the DNS class of the zone'
complete -c dnssec-verify -s E -d 'Specifies the cryptographic hardware to use, when applicable'
complete -c dnssec-verify -s I -d 'The format of the input zone file'
complete -c dnssec-verify -s o -d 'The zone origin'
complete -c dnssec-verify -s v -d 'Sets the debugging level'
complete -c dnssec-verify -s V -d 'Prints version information'
complete -c dnssec-verify -s q -d 'Quiet mode: Suppresses output'
complete -c dnssec-verify -s x -d 'Only verify that the DNSKEY RRset is signed with key-signing keys'
complete -c dnssec-verify -s z -d 'Ignore the KSK flag on the keys when determining whether the zone if correctl…'

