# dnsspoof
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnsspoof.8.gz
complete -c dnsspoof -s i -d 'Specify the interface to use'
complete -c dnsspoof -s f -d 'Specify the pathname of a file in hosts(5) format'

