# dnssec-importkey
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnssec-importkey.8.gz
complete -c dnssec-importkey -s f -d 'Zone file mode: instead of a public keyfile name, the argument is the DNS dom…'
complete -c dnssec-importkey -s K -d 'Sets the directory in which the key files are to reside'
complete -c dnssec-importkey -s L -d 'Sets the default TTL to use for this key when it is converted into a DNSKEY RR'
complete -c dnssec-importkey -s h -d 'Emit usage message and exit'
complete -c dnssec-importkey -s v -d 'Sets the debugging level'
complete -c dnssec-importkey -s V -d 'Prints version information'
complete -c dnssec-importkey -s P -d 'Sets the date on which a key is to be published to the zone'
complete -c dnssec-importkey -s D -d 'Sets the date on which the key is to be deleted'

