# dnssec-dsfromkey
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dnssec-dsfromkey.8.gz
complete -c dnssec-dsfromkey -s 1 -d 'An abbreviation for -a SHA1'
complete -c dnssec-dsfromkey -s 2 -d 'An abbreviation for -a SHA-256'
complete -c dnssec-dsfromkey -s a -d 'Specify a digest algorithm to use when converting DNSKEY records to DS records'
complete -c dnssec-dsfromkey -s A -d 'Include ZSKs when generating DS records'
complete -c dnssec-dsfromkey -s c -d 'Specifies the DNS class (default is IN)'
complete -c dnssec-dsfromkey -s C -d 'Generate CDS records rather than DS records'
complete -c dnssec-dsfromkey -s f -d 'Zone file mode: dnssec-dsfromkey\\(aqs final dnsname argument is the DNS domai…'
complete -c dnssec-dsfromkey -s h -d 'Prints usage information'
complete -c dnssec-dsfromkey -s K -d 'Look for key files or keyset- files in directory'
complete -c dnssec-dsfromkey -s s -d 'Keyset mode: dnssec-dsfromkey\\(aqs final dnsname argument is the DNS domain n…'
complete -c dnssec-dsfromkey -s T -d 'Specifies the TTL of the DS records.  By default the TTL is omitted'
complete -c dnssec-dsfromkey -s v -d 'Sets the debugging level'
complete -c dnssec-dsfromkey -s V -d 'Prints version information'

