# dnswalk
# Autogenerated from man page /usr/man/man1/dnswalk.1.gz
complete -c dnswalk -s r -d 'Recursively descend sub-domains of the specified domain.   Use with care'
complete -c dnswalk -s a -d 'Turn on warning of duplicate A records.   (see below)'
complete -c dnswalk -s d -d 'Print debugging and \'status\' information to stderr'
complete -c dnswalk -s m -d 'Perform checks only if the zone has been modified since the previous run'
complete -c dnswalk -s F -d 'perform "fascist" checking'
complete -c dnswalk -s i -d 'Suppress check for invalid characters in a domain name.   (see below)'
complete -c dnswalk -s l -d 'Perform "lame delegation" checking'

