# dosfslabel
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dosfslabel.8.gz
complete -c dosfslabel -s h -l help -d 'Displays a help message'
complete -c dosfslabel -s V -l version -d 'Shows version'

