# dsniff
# Autogenerated from man page /usr/lib/jvm/default/man/man8/dsniff.8.gz
complete -c dsniff -s c -d 'Perform half-duplex TCP stream reassembly, to handle asymmetrically routed tr…'
complete -c dsniff -s d -d 'Enable debugging mode'
complete -c dsniff -s m -d 'Enable automatic protocol detection'
complete -c dsniff -s n -d 'Do not resolve IP addresses to hostnames'
complete -c dsniff -s i -d 'Specify the interface to listen on'
complete -c dsniff -s p -d 'Rather than processing the contents of packets observed upon the network  pro…'
complete -c dsniff -s s -d 'Analyze at most the first snaplen bytes of each TCP connection, rather than t…'
complete -c dsniff -s f -d 'Load triggers from a services file'
complete -c dsniff -s t -d 'Load triggers from a comma-separated list, specified as port/proto=service (e'
complete -c dsniff -s r -d 'Read sniffed sessions from a savefile created with the -w option'
complete -c dsniff -s w -d 'Write sniffed sessions to savefile rather than parsing and printing them out'

