# edb
# Autogenerated from man page /usr/lib/jvm/default/man/man1/edb.1.gz
complete -c edb -l help -d 'Show usage and exit'
complete -c edb -l symbols -d 'generate symbols map for file <file>'
complete -c edb -l attach -d 'attach the process of PID <pid> to debugger'
complete -c edb -l run -d 'open <program> in debugger with optional [args. ]'
complete -c edb -l version -d 'show version string and exit'
complete -c edb -l dump-version -d 'show version and exit.  EXAMPLE edb --symbols /lib/libc. so. 6 > libc. so. 6'

