# espeakup
# Autogenerated from man page /usr/lib/jvm/default/man/man8/espeakup.8.gz
complete -c espeakup -s P -l pid-path --description 'Set the full path for the pid file espeakup uses when in daemon mode.'
complete -c espeakup -s V -l default-voice --description 'Set the espeak voice to be used by default.'
complete -c espeakup -s d -l debug --description 'run in the foreground, rather than becoming a daemon process.'
complete -c espeakup -s h -l help --description 'display a brief help message and exit.'
complete -c espeakup -s v -l version --description 'output version information and exit.'

