# espeakup
# Autogenerated from man page /usr/lib/jvm/default/man/man8/espeakup.8.gz
complete -c espeakup -s P -l pid-path -d 'Set the full path for the pid file espeakup uses when in daemon mode'
complete -c espeakup -s V -l default-voice -d 'Set the espeak voice to be used by default'
complete -c espeakup -s d -l debug -d 'run in the foreground, rather than becoming a daemon process'
complete -c espeakup -s h -l help -d 'display a brief help message and exit'
complete -c espeakup -s v -l version -d 'output version information and exit'

