# extract
# Autogenerated from man page /usr/lib/jvm/default/man/man1/extract.1.gz
complete -c extract -s b -d 'Display the output in BiBTeX format'
complete -c extract -s g -d 'Use grep-friendly output (all keywords on a single line for each file)'
complete -c extract -s h -d 'Print a brief summary of the options'
complete -c extract -s i -d 'Run plugins in-process (for debugging)'
complete -c extract -s l -d 'Use the specified libraries to extract keywords'
complete -c extract -s L -d 'Print a list of all known keyword types'
complete -c extract -s m -d 'Load the file into memory and perform extraction from memory (for debugging)'
complete -c extract -s n -d 'Do not use the default set of extractors (typically all standard extractors, …'
complete -c extract -s p -d 'Print only the keywords matching the specified type'
complete -c extract -s v -d 'Print the version number and exit'
complete -c extract -s V -d 'Be verbose'
complete -c extract -s x -d 'Exclude keywords of the specified type from the output'

