# fc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fc.1p.gz
complete -c fc -o eeditor --description 'Use the editor named by R editor to edit the commands.'
complete -c fc -s l --description '(The letter ell. ) List the commands rather than invoking an editor on them.'
complete -c fc -s n --description 'Suppress command numbers when listing with  -l .'
complete -c fc -s r --description 'Reverse the order of the commands listed (with  -l ) or edited (with neither …'
complete -c fc -s e --description 'Use the editor named by editor to edit the commands.'
complete -c fc -s s --description '.'
complete -c fc -o number --description 'A negative decimal number representing the command that was executed number o…'

