# file
# Autogenerated from man page /usr/lib/jvm/default/man/man1/file.1p.gz
complete -c file -o Mfile --description 'Specify the name of a file containing position-sensitive tests that shall be …'
complete -c file -s M --description 'and.'

