# filesnarf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/filesnarf.8.gz
complete -c filesnarf -s i -d 'Specify the interface to listen on'
complete -c filesnarf -s p -d 'Process packets from the specified PCAP capture file instead of the network'
complete -c filesnarf -s v -d '"Versus" mode.  Invert the sense of matching, to select non-matching files'

