# foremost
# Autogenerated from man page /usr/lib/jvm/default/man/man8/foremost.8.gz
complete -c foremost -s h -d 'Show a help screen and exit'
complete -c foremost -s V -d 'Show copyright information and exit'
complete -c foremost -s d -d 'Turn on indirect block detection, this works well for Unix file systems'
complete -c foremost -s T -d 'Time stamp the output directory so you don\'t have to delete the output dir wh…'
complete -c foremost -s v -d 'Enables verbose mode'
complete -c foremost -s q -d 'Enables quick mode'
complete -c foremost -s Q -d 'Enables Quiet mode.  Most error messages will be suppressed. br'
complete -c foremost -s w -d 'Enables write audit only mode.   No files will be extracted. br'
complete -c foremost -s a -d 'Enables write all headers, perform no error detection in terms of corrupted f…'
complete -c foremost -s b -d 'Allows you to specify the block size used in foremost'
complete -c foremost -s k -d 'Allows you to specify the chunk size used in foremost'
complete -c foremost -s i -d 'The file is used as the input file'
complete -c foremost -s o -d 'Recovered files are written to the directory directory'
complete -c foremost -s c -d 'Sets the configuration file to use'
complete -c foremost -s s -d 'Skips number blocks in the input file before beginning the search for headers'

