# ftester
# Autogenerated from man page /usr/lib/jvm/default/man/man8/ftester.8.gz
complete -c ftester -s c -d 'Injects a single packet (override -f option)'
complete -c ftester -s d -d 'Delay in milliseconds between each packet injection'
complete -c ftester -s e -d 'See the   IDS EVASION  section'
complete -c ftester -s f -d 'Read configuration from file'
complete -c ftester -s F -d 'When in connection spoofing mode terminate (FIN handshake) the created connec…'
complete -c ftester -s g -d 'Split TCP and UDP marked packets in the specified number of IP fragments, use…'
complete -c ftester -s k -d 'Set a custom checksum instead of the right one when sending packets, useful t…'
complete -c ftester -s p -d 'Specify the number of TCP segments when splitting the tcp stream in evasion m…'
complete -c ftester -s r -d 'When in connection spoofing mode reset (RST packet) the created connection, u…'
complete -c ftester -s s -d 'Sleep time in seconds for waiting connection spoofing replies, see \'connectio…'
complete -c ftester -s t -d 'Time to live that makes the ttl1/ttl2 evasion option packets visible to the I…'
complete -c ftester -s m -d 'Custom marker string that is appended to the standard signature in generated …'
complete -c ftester -s v -d 'Prints to stdout injected packets and be verbose. SS ftestd:'
complete -c ftester -s i -d 'Listen on interface, if not specified will default to the first configured on…'

