# fwupd-dbxtool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fwupd-dbxtool.1.gz
complete -c fwupd-dbxtool -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c fwupd-dbxtool -s v -l verbose --description 'Show extra debugging information.'
complete -c fwupd-dbxtool -l version --description 'Show the calculated version of the dbx.'
complete -c fwupd-dbxtool -s l -l list --description 'List entries in dbx.'
complete -c fwupd-dbxtool -s a -l apply --description 'Apply update files.'
complete -c fwupd-dbxtool -s d -l dbx --description 'Specify the dbx database file.'
complete -c fwupd-dbxtool -s f -l force --description 'Apply update even when not advised.'

