# ges-launch-1
# Autogenerated from man page /usr/share/man/man1/ges-launch-1.0.1.gz
complete -c ges-launch-1 -l help-informative -d 'Show informative options SEE ALSO For more detailed info and some examples of…'

