# git-mktag
# Autogenerated from man page /usr/lib/jvm/default/man/man1/git-mktag.1.gz
complete -c git-mktag -l strict --description 'By default mktag turns on the equivalent of git-fsck(1) --strict mode.'
complete -c git-mktag -l no-strict --description 'to disable it.'

