# gps2udp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gps2udp.1.gz
complete -c gps2udp -s '?' -s h -l help --description '-Print a usage message and exit.'
complete -c gps2udp -s a -l ais --description 'Send only AIS messages.'
complete -c gps2udp -s b -l daemon --description 'Causes gps2udp to run as a daemon.'
complete -c gps2udp -s c -l count --description 'Exit after COUNT sentences are sent.'
complete -c gps2udp -s d -l debug --description 'Set debug level to LVL.  LVL = 0 prints nothing.'
complete -c gps2udp -s j -l json --description 'Causes JSON sentences to be output.'
complete -c gps2udp -s n -l nmea --description 'Causes NMEA sentences to be output.'
complete -c gps2udp -s t -l tpv --description 'Only output TPV sentences.  Implies --json.'
complete -c gps2udp -s u -l udp --description 'UDP destination for output sentenses (up to five destinations).'
complete -c gps2udp -s v -s V -l version --description 'Prints the program version, then exit.  -v is deprecated December 2020.'
complete -c gps2udp -o Print --description '.'

