# gpscat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpscat.1.gz
complete -c gpscat -s '?' -s h -l help --description '.'
complete -c gpscat -s D -l debug --description '.'
complete -c gpscat -s p -l packetizer --description '.'
complete -c gpscat -s s -l speed --description '.'
complete -c gpscat -s t -l typeflag --description '.'
complete -c gpscat -s V -l version --description '.'

