# gpscsv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpscsv.1.gz
complete -c gpscsv -s '?' -s h -l help --description 'Show help information and exit.'
complete -c gpscsv -s c -l class --description 'Select the JSON class messages of type MCLASS.  Default is TPV.'
complete -c gpscsv -l cvt-isotime --description 'Convert fields named "time" from ISO time to UNIX time.'
complete -c gpscsv -s D -l debug --description 'Set debug level to LVL.  Default 0.'
complete -c gpscsv -l device --description 'The DEVICE on the gpsd to connect to.  Defaults to all.'
complete -c gpscsv -s f -o fields --description 'The FIELDS from the JSON message to dump to the output.'
complete -c gpscsv -l file --description 'Read JSON from FILE instead of from gpsd.'
complete -c gpscsv -l header --description 'Set header style to HEADER.'
complete -c gpscsv -l host --description 'Connect to the gpsd on HOST.  Defaults to localhost.'
complete -c gpscsv -s n -l count --description 'Exit after outputting COUNT records.  Set COUNT to 0 to disable.'
complete -c gpscsv -l port --description 'Use PORT to connect to gpsd.  Defaults to 2947.'
complete -c gpscsv -l separator --description 'Use SEPARATOR as the field separator.'
complete -c gpscsv -s V -l version --description 'Show gpscsv version, and exit.'
complete -c gpscsv -s x -l seconds --description 'Exit after SECONDS number of seconds have passed.'

