# gpsctl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpsctl.1.gz
complete -c gpsctl -s '?' -s h -l help --description '.'
complete -c gpsctl -s b -l binary --description '.'
complete -c gpsctl -s c -l rate --description '.'
complete -c gpsctl -s D -l debug --description '.'
complete -c gpsctl -s e -l echo --description '.'
complete -c gpsctl -s t --description 'option without specifying a device.'
complete -c gpsctl -s f -l force --description '.'
complete -c gpsctl -s l -l list --description '.'
complete -c gpsctl -s n -l nmea --description '.'
complete -c gpsctl -s r -l reset --description '.'
complete -c gpsctl -s R -l rmshm --description '.'
complete -c gpsctl -s s -l speed --description '.'
complete -c gpsctl -l type --description '.'
complete -c gpsctl -s T -l timeout --description '.'
complete -c gpsctl -s V -l version --description '.'
complete -c gpsctl -s x -l ship --description '.'

