# gpsd
# Autogenerated from man page /usr/lib/jvm/default/man/man8/gpsd.8.gz
complete -c gpsd -s '?' -s h -l -help --description '.'
complete -c gpsd -s b -l readonly --description '.'
complete -c gpsd -s D -l debug --description '.'
complete -c gpsd -s F -l sockfile --description '.'
complete -c gpsd -s f -l framing --description '.'
complete -c gpsd -s G -l listenany --description '.'
complete -c gpsd -s l -l drivers --description '.'
complete -c gpsd -s N -l foreground --description '.'
complete -c gpsd -s p -l passive --description '.'
complete -c gpsd -s P -l pidfile --description '.'
complete -c gpsd -s r -l badtime --description '.'
complete -c gpsd -l port -s S --description '.'
complete -c gpsd -s s -l speed --description '.'
complete -c gpsd -s V -l version --description '.'

