# gpsdecode
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpsdecode.1.gz
complete -c gpsdecode -s '?' -s h -l help --description 'Output a usage mssage, then exit.'
complete -c gpsdecode -s c -l json --description 'Sets the AIS dump format to separate fields with an ASCII pipe symbol.'
complete -c gpsdecode -s d -l decode --description 'Decode packets presented on standard input to standard output.'
complete -c gpsdecode -s D -l debug --description 'Set the debug verbosity level to LVL.'
complete -c gpsdecode -s e -l encode --description 'Encode JSON on standard input to JSON on standard output.'
complete -c gpsdecode -s j --description 'Sets the output dump format to JSON (the default behavior).'
complete -c gpsdecode -s m -l minlength --description 'Dump minimum lengths for each packet type in the input (ignoring comment pack…'
complete -c gpsdecode -s n -l nmea --description 'Dump the generated pseudo-NME0183.'
complete -c gpsdecode -s s -l split24 --description 'Report AIS Type 24 sentence halves separately rather than attempting to aggre…'
complete -c gpsdecode -s t -l types --description 'A comma-separated list of numeric types.'
complete -c gpsdecode -s u -l unsscaled --description 'Suppress scaling of AIS data to float quantities and text expansion of numeri…'
complete -c gpsdecode -s v -l verbose --description 'Dump textual packets to output as they are received on input, immediately pre…'
complete -c gpsdecode -s V -l version --description 'Print version number, then exit.'
complete -c gpsdecode -l ais --description 'option, dump lines are values of AIS payload fields, pipe-separated, in the o…'

