# gpsinit
# Autogenerated from man page /usr/lib/jvm/default/man/man8/gpsinit.8.gz
complete -c gpsinit -s h --description '.'
complete -c gpsinit -s n --description '.'
complete -c gpsinit -s s --description '.'
complete -c gpsinit -s V --description '.'

