# gpsplot
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpsplot.1.gz
complete -c gpsplot -s '?' -s h -l help --description 'Print a usage message and exit.'
complete -c gpsplot -s d -l debug --description 'Set debug level to LVL.'
complete -c gpsplot -l device --description 'The DEVICE on the gpsd to connect to.  Defaults to all.'
complete -c gpsplot -l fields --description 'The code for the fields to plot.'
complete -c gpsplot -l file --description 'Read JSON from FILE instead of from gpsd.'
complete -c gpsplot -l host --description 'Connect to the gpsd on HOST (server).  Defaults to localhost.'
complete -c gpsplot -l plottype --description 'The type of plot to make.'
complete -c gpsplot -s n -l count --description 'Exit after COUNT plot messages.'
complete -c gpsplot -s p -l port --description 'Use PORT to connect to gpsd.  Defaults to 2947.'
complete -c gpsplot -s V -l version --description 'Print the program version and exit.'
complete -c gpsplot -s x -l seconds --description 'Wait for SECONDS seconds before exiting.  Set to zero to diable.  Default 0.'

