# gpssubframe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpssubframe.1.gz
complete -c gpssubframe -s '?' -s h -l help --description '-Print a usage message and exit.'
complete -c gpssubframe -s c -l count --description 'Exit after COUNT subframe messages.'
complete -c gpssubframe -l device --description 'Connect to device DEVICE on gpsd host.'
complete -c gpssubframe -s D -l debug --description 'Set debug level to LVL.'
complete -c gpssubframe -l file --description 'Read JSON from FILE instead of from gpsd.'
complete -c gpssubframe -l host --description 'Connect to gpsd on host HOST.'
complete -c gpssubframe -l port --description 'Connect to gpsd on port PORT.'
complete -c gpssubframe -l progress --description 'Print progress reports as messages are received.'
complete -c gpssubframe -l satpos --description 'Compute GPS satellite positions before exit.'
complete -c gpssubframe -l time --description 'Compute satellite position at time SEC in POSIX seconds.'
complete -c gpssubframe -l test --description 'Run --satpos selftest code.'
complete -c gpssubframe -s V -l version --description 'Print the program version, then exit.'
complete -c gpssubframe -s x -l seconds --description 'Seconds of messages to parse.  0 to disable.'
complete -c gpssubframe -o Print --description '.'

