# gpxlogger
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gpxlogger.1.gz
complete -c gpxlogger -s '?' -s h -l help --description 'Print a summary of options and then exit.'
complete -c gpxlogger -s d -l daemonize --description 'Run as a daemon in background.'
complete -c gpxlogger -s D -l debug --description 'Sets the debug level; it is primarily for troubleshooting.'
complete -c gpxlogger -s i -l interval --description 'A new track is created if there\\*(Aqs no fix written for an interval of SECON…'
complete -c gpxlogger -s l -l exports --description 'List all possible options for -e, --export.'
complete -c gpxlogger -s m -l minmove --description 'Sets a minimum move distance in meters (it may include a fractional decimal p…'
complete -c gpxlogger -s r -l reconnect --description 'Retry when GPSd loses the fix.  Without -r, gpxlogger would quit in this case.'
complete -c gpxlogger -s V -l version --description 'Dump the package version and exit.'
complete -c gpxlogger -s e -l export --description 'one of the colon-terminated method names from the.'
complete -c gpxlogger -s f -l output --description 'option, which directs output to a specified logfile.'

