# halberd
# Autogenerated from man page /usr/man/man1/halberd.1.gz
complete -c halberd -l version -d 'show program\'s version number and exit'
complete -c halberd -s h -l help -d 'show this help message and exit'
complete -c halberd -s v -l verbose -d 'explain what is being done'
complete -c halberd -s q -l quiet -d 'run quietly'
complete -c halberd -s d -l debug -d 'enable debugging information'
complete -c halberd -s t -l time -d 'time (in seconds) to spend scanning the target'
complete -c halberd -s p -l parallelism -d 'specify the number of parallel threads to use'
complete -c halberd -s u -l urlfile -d 'read URLs from FILE'
complete -c halberd -s o -l out -d 'write report to the specified file'
complete -c halberd -s a -l address -d 'specify address to scan'
complete -c halberd -s r -l read -d 'load clues from the specified file'
complete -c halberd -s w -l write -d 'save clues to the specified directory'
complete -c halberd -l config -d 'use alternative configuration file'

