# iconv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/iconv.1p.gz
complete -c iconv -o ffromcodeset --description 'br Identify the codeset of the input file.'
complete -c iconv -o ttocodeset --description 'Identify the codeset to be used for the output file.'

