# ipcrm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ipcrm.1p.gz
complete -c ipcrm -o qmsgid --description 'Remove the message queue identifier R msgid from the system and destroy the m…'
complete -c ipcrm -o mshmid --description 'Remove the shared memory identifier R shmid from the system.'
complete -c ipcrm -o ssemid --description 'Remove the semaphore identifier R semid from the system and destroy the set o…'
complete -c ipcrm -o Qmsgkey --description 'Remove the message queue identifier, created with key R msgkey , from the sys…'
complete -c ipcrm -o Mshmkey --description 'Remove the shared memory identifier, created with key R shmkey , from the sys…'

