# iwmon
# Autogenerated from man page /usr/lib/jvm/default/man/man1/iwmon.1.gz
complete -c iwmon -l version -s v -d 'Show version number and exit'
complete -c iwmon -l help -s h -d 'Show help message and exit'

