# jcmd-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jcmd-openjdk15.1.gz
complete -c jcmd-openjdk15 -o all --description 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low.'
complete -c jcmd-openjdk15 -s l --description '(BOOLEAN, false) VM.'
complete -c jcmd-openjdk15 -s i --description '(BOOLEAN, false) [bu] 2.'
complete -c jcmd-openjdk15 -s s --description 'subclasses.'
complete -c jcmd-openjdk15 -o verbose --description 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table.'
complete -c jcmd-openjdk15 -o date --description '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low.'

