# jdb-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jdb-openjdk15.1.gz
complete -c jdb-openjdk15 -o help --description 'Displays a help message.'
complete -c jdb-openjdk15 -o sourcepath --description 'Uses the specified path to search for source files in the specified path.'
complete -c jdb-openjdk15 -o attach --description 'Attaches the debugger to a running JVM with the default connection mechanism.'
complete -c jdb-openjdk15 -o listen --description 'Waits for a running JVM to connect to the specified address with a standard c…'
complete -c jdb-openjdk15 -o listenany --description 'Waits for a running JVM to connect at any available address using a standard …'
complete -c jdb-openjdk15 -o launch --description 'Starts the debugged application immediately upon startup of the jdb command.'
complete -c jdb-openjdk15 -o listconnectors --description 'Lists the connectors available in this JVM.'
complete -c jdb-openjdk15 -o connect --description 'Connects to the target JVM with the named connector and listed argument value…'
complete -c jdb-openjdk15 -o dbgtrace --description 'Prints information for debugging the jdb command.'
complete -c jdb-openjdk15 -o tclient --description 'Runs the application in the Java HotSpot VM client.'
complete -c jdb-openjdk15 -o tserver --description 'Runs the application in the Java HotSpot VM server.'
complete -c jdb-openjdk15 -o Joption --description 'Passes option to the JVM, where option is one of the options described on the…'
complete -c jdb-openjdk15 -s v -o 'verbose[:class' --description 'Turns on the verbose mode.'
complete -c jdb-openjdk15 -o Dname --description 'Sets a system property.'
complete -c jdb-openjdk15 -o classpath --description 'Lists directories separated by colons in which to look for classes.'
complete -c jdb-openjdk15 -s X --description 'A nonstandard target JVM option.'

