# jfr-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jfr-openjdk15.1.gz
complete -c jfr-openjdk15 -l xml --description 'Print the recording in XML format.'
complete -c jfr-openjdk15 -l json --description 'Print the recording in JSON format.'
complete -c jfr-openjdk15 -l categories --description 'Select events matching a category name.'
complete -c jfr-openjdk15 -l events --description 'Select events matching an event name.'
complete -c jfr-openjdk15 -l stack-depth --description 'Number of frames in stack traces, by default 5 <file> Location of the recordi…'
complete -c jfr-openjdk15 -l output --description 'The location to write the disassembled file, by default the current directory.'
complete -c jfr-openjdk15 -l max-chunks --description 'Maximum number of chunks per file, by default 5.'
complete -c jfr-openjdk15 -l max-size --description 'Maximum number of bytes per file.'

