# jhsdb-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jhsdb-openjdk15.1.gz
complete -c jhsdb-openjdk15 -l serverid --description 'An optional unique ID for this debug server.'
complete -c jhsdb-openjdk15 -l rmiport --description 'Sets the port number to which the RMI connector is bound.'
complete -c jhsdb-openjdk15 -l registryport --description 'Sets the RMI registry port.'
complete -c jhsdb-openjdk15 -l hostname --description 'Sets the hostname the RMI connector is bound.'
complete -c jhsdb-openjdk15 -l flags --description 'Prints the VM flags.'
complete -c jhsdb-openjdk15 -l sysprops --description 'Prints the Java system properties.'
complete -c jhsdb-openjdk15 -l heap --description 'Prints the java heap summary.'
complete -c jhsdb-openjdk15 -l binaryheap --description 'Dumps the java heap in hprof binary format.'
complete -c jhsdb-openjdk15 -l dumpfile --description 'The name of the dumpfile.'
complete -c jhsdb-openjdk15 -l histo --description 'Prints the histogram of java object heap.'
complete -c jhsdb-openjdk15 -l clstats --description 'Prints the class loader statistics.'
complete -c jhsdb-openjdk15 -l finalizerinfo --description 'Prints the information on objects awaiting finalization.'
complete -c jhsdb-openjdk15 -l locks --description 'Prints the java. util. concurrent locks information.'
complete -c jhsdb-openjdk15 -l mixed --description 'Attempts to print both java and native frames if the platform allows it.'
complete -c jhsdb-openjdk15 -l all --description 'Prints all performance counters.'

