# jinfo-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jinfo-openjdk15.1.gz
complete -c jinfo-openjdk15 -o flag --description 'Prints the name and value of the specified command-line flag.'
complete -c jinfo-openjdk15 -o ']name' --description 'Enables or disables the specified Boolean command-line flag.'
complete -c jinfo-openjdk15 -o flags --description 'Prints command-line flags passed to the JVM.'
complete -c jinfo-openjdk15 -o sysprops --description 'Prints Java system properties as name-value pairs.'
complete -c jinfo-openjdk15 -s h -o help --description 'Prints a help message.'

