# join
# Autogenerated from man page /usr/lib/jvm/default/man/man1/join.1p.gz
complete -c join -o afile_number --description 'br Produce a line for each unpairable line in file R file_number , where R fi…'
complete -c join -o estring --description 'Replace empty output fields in the list selected by  -o with the string R str…'
complete -c join -o olist --description 'Construct the output line to comprise the fields specified in R list , each e…'
complete -c join -o tchar --description 'Use character R char as a separator, for both input and output.'
complete -c join -o vfile_number --description 'br Instead of the default output, produce a line only for each unpairable lin…'
complete -c join -o 1field --description 'Join on the R field th field of file 1.'
complete -c join -s b --description 'on the fields on which they shall be joined, by default the first in each lin…'
complete -c join -o j1 --description '.'
complete -c join -o j2 --description 'options, and a form of the.'

