# kill
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kill.1p.gz
complete -c kill -o ssignal_name --description 'br Specify the signal to send, using one of the symbolic names defined in the…'
complete -c kill -o signal_name --description 'br Equivalent to  -s R signal_name .'
complete -c kill -o signal_number --description 'br Specify a non-negative decimal integer, R signal_number , representing the…'

