# libinput-analyze-touch-down-state
# Autogenerated from man page /usr/lib/jvm/default/man/man1/libinput-analyze-touch-down-state.1.gz
complete -c libinput-analyze-touch-down-state -l help --description 'Print help.'
complete -c libinput-analyze-touch-down-state -l use-st --description 'Use the single-touch BTN_TOOL_ bits instead of the slot state.'

