# localedef
# Autogenerated from man page /usr/lib/jvm/default/man/man1/localedef.1p.gz
complete -c localedef -o fcharmap --description 'Specify the pathname of a file containing a mapping of character symbols and …'
complete -c localedef -o iinputfile --description 'The pathname of a file containing the source definitions.'
complete -c localedef -s 1 --description 'the result will be undefined.'

