# lxc-create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lxc-create.1.gz
complete -c lxc-create -l config --description 'Specify the configuration file to configure the virtualization and isolation …'
complete -c lxc-create -l template --description '\'template\' is the short name of an existing \'lxc-template\' script that is cal…'
complete -c lxc-create -l bdev --description '\'backingstore\' is one of \'dir\', \'lvm\', \'loop\', \'btrfs\', \'zfs\', \'rbd\', or \'bes…'
complete -c lxc-create -l dir --description 'that the container rootfs should be placed under the specified path, rather t…'
complete -c lxc-create -l lvname --description 'named \\fIlvname1 rather than the default, which is the container name.'
complete -c lxc-create -l thinpool --description 'LV as a thin-provisioned volume in the pool named \\fIthinpool1 rather than th…'
complete -c lxc-create -l fstype --description 'filesystem on the LV, rather than the default, which is ext4.'
complete -c lxc-create -l fssize --description 'filesystem) of size SIZE rather than the default, which is 1G.'
complete -c lxc-create -l rbdname --description '.'
complete -c lxc-create -l rbdpool --description '.'

