# lxc-start
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lxc-start.1.gz
complete -c lxc-start -l pidfile --description 'Create a file with the process id.'
complete -c lxc-start -l rcfile --description 'Specify the configuration file to configure the virtualization and isolation …'
complete -c lxc-start -l console --description 'Specify a device to use for the container\'s console, for example /dev/tty8.'
complete -c lxc-start -l console-log --description 'Specify a file to log the container\'s console output to.'
complete -c lxc-start -l define --description 'Assign value VAL to configuration variable KEY.'
complete -c lxc-start -l close-all-fds --description '.'

