# lxc-autostart
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lxc-autostart.1.gz
complete -c lxc-autostart -l reboot --description 'Request a reboot of the container.'
complete -c lxc-autostart -l shutdown --description 'Request a clean shutdown.'
complete -c lxc-autostart -l kill --description 'Rather than requesting a clean shutdown of the container, explicitly kill all…'
complete -c lxc-autostart -l list --description 'Rather than performing the action, just print the container name and wait del…'
complete -c lxc-autostart -l timeout --description 'Wait TIMEOUT seconds before hard-stopping the container.'
complete -c lxc-autostart -l group --description 'Comma separated list of groups to select (defaults to those without a lxc.'
complete -c lxc-autostart -s a --description 'AUTOSTART AND SYSTEM BOOT The lxc-autostart command is used as part of the LX…'

