# lxc-copy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lxc-copy.1.gz
complete -c lxc-copy -l newname --description 'The name for the copy.'
complete -c lxc-copy -l newpath --description 'The path for the copy.'
complete -c lxc-copy -l rename --description 'Rename the original container.'
complete -c lxc-copy -l snapshot --description 'Create a snapshot of the original container.'
complete -c lxc-copy -l allowrunning --description 'Allow the creation of a Snapshot of an already running container.'
complete -c lxc-copy -l mount --description 'Specify a mount for a snapshot The opts argument for the mount type can by of…'
complete -c lxc-copy -l tmpfs --description 'When this option is specified the ephemeral container will be placed on a tmp…'
complete -c lxc-copy -l backingstorage --description 'Specify the backing storage type to be used for the copy where \'backingstorag…'
complete -c lxc-copy -l fssize --description 'Specify the size for an \'lvm\' filesystem.'
complete -c lxc-copy -l keepname --description 'When this option is specified the hostname of the original container will be …'
complete -c lxc-copy -l keepdata --description 'When this option is specified with -e a non-ephemeral container is created an…'
complete -c lxc-copy -s e --description '.'
complete -c lxc-copy -s D --description 'container is created and started.'
complete -c lxc-copy -s N --description '.'
complete -c lxc-copy -s m --description 'bind=/src1:/dest1:ro,bind=/src2:ro,overlay=/src3:/dest3.'

