# macof
# Autogenerated from man page /usr/lib/jvm/default/man/man8/macof.8.gz
complete -c macof -s i -d 'Specify the interface to send on'
complete -c macof -s s -d 'Specify source IP address'
complete -c macof -s d -d 'Specify destination IP address'
complete -c macof -s e -d 'Specify target hardware address'
complete -c macof -s x -d 'Specify TCP source port'
complete -c macof -s y -d 'Specify TCP destination port'
complete -c macof -s n -d 'Specify the number of packets to send'

