# mailsnarf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/mailsnarf.8.gz
complete -c mailsnarf -s i -d 'Specify the interface to listen on'
complete -c mailsnarf -s p -d 'Process packets from the specified PCAP capture file instead of the network'
complete -c mailsnarf -s v -d '"Versus" mode.  Invert the sense of matching, to select non-matching messages'

