# make
# Autogenerated from man page /usr/lib/jvm/default/man/man1/make.1p.gz
complete -c make -o fmakefile --description 'Specify a different makefile.'
complete -c make -s P --description 'to achieve the portable behavior.  Therefore, the special target .'

