# memcp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/memcp.1.gz
complete -c memcp -l servers --description 'or via the environment variable: MEMCACHED_SERVERS If you do not specify eith…'
complete -c memcp -l help --description '.'

