# memflush
# Autogenerated from man page /usr/lib/jvm/default/man/man1/memflush.1.gz
complete -c memflush -l servers --description 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memflush -l help --description '.'

