# memstat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/memstat.1.gz
complete -c memstat -l servers --description 'or via the environment variable: \'MEMCACHED_SERVERS, --args\' which can be use…'
complete -c memstat -l help --description '.'
complete -c memstat -l analyze --description '.'

