# memslap
# Autogenerated from man page /usr/lib/jvm/default/man/man1/memslap.1.gz
complete -c memslap -l servers --description 'or via the environment variable: MEMCACHED_SERVERS For a full list of operati…'
complete -c memslap -l help --description '.'

