# msgsnarf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/msgsnarf.8.gz
complete -c msgsnarf -s i -d 'Specify the interface to listen on'
complete -c msgsnarf -s p -d 'Process packets from the specified PCAP capture file instead of the network'
complete -c msgsnarf -s v -d '"Versus" mode.  Invert the sense of matching, to select non-matching messages'

