# mt-st
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mt-st.1.gz
complete -c mt-st -s h --description 'option.  The version of mt is printed with the.'
complete -c mt-st -s v --description 'or.'
complete -c mt-st -l version --description 'option.'
complete -c mt-st -s f --description 'or.'
complete -c mt-st -s t --description 'option.'

