# named-checkconf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/named-checkconf.8.gz
complete -c named-checkconf -s h -d 'Print the usage summary and exit'
complete -c named-checkconf -s j -d 'When loading a zonefile read the journal if it exists'
complete -c named-checkconf -s l -d 'List all the configured zones'
complete -c named-checkconf -s c -d 'Check "core" configuration only'
complete -c named-checkconf -s i -d 'Ignore warnings on deprecated options'
complete -c named-checkconf -s p -d 'Print out the named'
complete -c named-checkconf -s t -d 'Chroot to directory so that include directives in the configuration file are …'
complete -c named-checkconf -s v -d 'Print the version of the named-checkconf program and exit'
complete -c named-checkconf -s x -d 'When printing the configuration files in canonical form, obscure shared secre…'
complete -c named-checkconf -s z -d 'Perform a test load of all master zones found in named. conf'

