# nfsv4
# Autogenerated from man page /usr/lib/jvm/default/man/man8/nfsv4.exportd.8.gz
complete -c nfsv4 -s d -l debug --description 'Turn on debugging.  Valid kinds are: all, auth, call, general and parse.'
complete -c nfsv4 -s F -l foreground --description 'Run in foreground (do not daemonize).'
complete -c nfsv4 -s h -l help --description 'Display usage message.'
complete -c nfsv4 -s t -l num-threads -l num-threads --description 'This option specifies the number of worker threads that rpc. mountd spawns.'

