# nl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nl.1p.gz
complete -c nl -o btype --description 'Specify which logical page body lines shall be numbered.'
complete -c nl -o ddelim --description 'Specify the delimiter characters that indicate the start of a logical page se…'
complete -c nl -o ftype --description 'Specify the same as  b R type except for footer.'
complete -c nl -o htype --description 'Specify the same as  b R type except for header.'
complete -c nl -o iincr --description 'Specify the increment value used to number logical page lines.'
complete -c nl -o lnum --description 'Specify the number of blank lines to be considered as one.'
complete -c nl -o nformat --description 'Specify the line numbering format.'
complete -c nl -o ssep --description 'Specify the characters used in separating the line number and the correspondi…'
complete -c nl -o vstartnum --description 'Specify the initial value used to number logical page lines.'

