# ntpshmmon
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ntpshmmon.1.gz
complete -c ntpshmmon -s '?' -s h -l help --description 'Display program usage and exit.'
complete -c ntpshmmon -s n -l count --description 'Set maximum number of samples to collect to COUNT.'
complete -c ntpshmmon -s o -l offset --description 'Replace the "Seen@" column with the "Offset" column.'
complete -c ntpshmmon -s s -l rmshm --description 'Remove all SHM segments used by GPSD.'
complete -c ntpshmmon -s t -l seconds --description 'Set maximum time to collect samples in seconds to SECONDS.'
complete -c ntpshmmon -s v -l verbose --description 'Enable verbose status messages.'
complete -c ntpshmmon -s V -l version --description 'Display program version and exit.'

