# nvme-zns-id-ns
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-id-ns.1.gz
complete -c nvme-zns-id-ns -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-id-ns -s v -l verbose --description 'Increase the information detail in the output.'
complete -c nvme-zns-id-ns -s o -l output-format --description 'Set the reporting format to normal, json, or binary.'

