# nvme-zns-zone-mgmt-send
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-zone-mgmt-send.1.gz
complete -c nvme-zns-zone-mgmt-send -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-zone-mgmt-send -s s -l start-lba --description 'The starting LBA of the zone to manage send.'
complete -c nvme-zns-zone-mgmt-send -s l -l data-len --description 'Send data buffer length.'
complete -c nvme-zns-zone-mgmt-send -l select-all -s a --description 'Send command to all zones.'
complete -c nvme-zns-zone-mgmt-send -s z -l zsa --description 'Zone send action.'
complete -c nvme-zns-zone-mgmt-send -s d -o data --description 'Optional file for data (default stdin).'

