# nvme-zns-set-zone-desc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-set-zone-desc.1.gz
complete -c nvme-zns-set-zone-desc -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-set-zone-desc -s s -l start-lba --description 'The starting LBA of the zone to manage send.'
complete -c nvme-zns-set-zone-desc -s d -o data --description 'Optional file for data (default stdin).'

