# nvme-micron-selective-download
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-micron-selective-download.1.gz
complete -c nvme-micron-selective-download -s f -l fw --description 'name of the firmware image file.'
complete -c nvme-micron-selective-download -s s -l select --description 'flag that has following values.'

