# nvme-zns-zone-append
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-zone-append.1.gz
complete -c nvme-zns-zone-append -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-zone-append -s s -l zslba -s z -l data-size --description 'Size of data, in bytes.'
complete -c nvme-zns-zone-append -s y -l metadata-size --description 'Size of metadata in bytes.'
complete -c nvme-zns-zone-append -s d -l data --description 'Data file providing the data to write.'
complete -c nvme-zns-zone-append -s M -l metadata --description 'Metadata file, if necessary.'
complete -c nvme-zns-zone-append -s l -l limited-retry --description 'Sets the limited retry flag.'
complete -c nvme-zns-zone-append -s f -l force-unit-access --description 'Set the force-unit access flag.'
complete -c nvme-zns-zone-append -s r -l ref-tag --description 'Optional reftag when used with protection information.'
complete -c nvme-zns-zone-append -s m -l app-tag-mask --description 'Optional application tag mask when used with protection information.'
complete -c nvme-zns-zone-append -s a -l app-tag --description 'Optional application tag when used with protection information.'
complete -c nvme-zns-zone-append -s p -l prinfo --description 'Protection Information field definition.'

