# nvme-zns-zone-mgmt-recv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-zone-mgmt-recv.1.gz
complete -c nvme-zns-zone-mgmt-recv -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-zone-mgmt-recv -s s -l start-lba --description 'The starting LBA of the zone to manage receive.'
complete -c nvme-zns-zone-mgmt-recv -s z -l zra --description 'Zone Receive Action.'
complete -c nvme-zns-zone-mgmt-recv -s f -l zra-spec-feat --description 'Enable Zone Receive Action Specific features.'
complete -c nvme-zns-zone-mgmt-recv -s o -l output-format --description 'Output format: normal|json|binary.'
complete -c nvme-zns-zone-mgmt-recv -l data-len -s l --description '.'
complete -c nvme-zns-zone-mgmt-recv -s a -l zrasf --description '.'

