# nvme-id-iocs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-id-iocs.1.gz
complete -c nvme-id-iocs -s c -l controller-id -d 'Retrieve the identify I/O Command set data structure for the given cntid'

