# nvme-copy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-copy.1.gz
complete -c nvme-copy -l sdlba -s d --description '64-bit addr of first destination logical block.'
complete -c nvme-copy -l blocks -s b --description 'Comma separated list of the number of blocks in each range.'
complete -c nvme-copy -l slbs -s s --description 'Comma separated list of the starting blocks in each range.'
complete -c nvme-copy -l limited-retry -s l --description 'Sets the limited retry flag.'
complete -c nvme-copy -l force-unit-access -s f --description 'Set the force-unit access flag.'
complete -c nvme-copy -l prinfow -s p --description 'Protection Information field write definition.'
complete -c nvme-copy -l prinfor -s P --description 'Protection Information field read definition.'
complete -c nvme-copy -l ref-tag -s r --description 'initial lba reference tag.'
complete -c nvme-copy -l expected-ref-tags -s R --description 'expected lba reference tags (comma-separated list).'
complete -c nvme-copy -l app-tag -s a --description 'lba app tag.'
complete -c nvme-copy -l expected-app-tags -s A --description 'expected lba app tags (comma-separated list).'
complete -c nvme-copy -l app-mask -s m --description 'lba tag mask.'
complete -c nvme-copy -l expected-app-masks -s M --description 'expected lba tag masks (comma-separated list).'
complete -c nvme-copy -l dir-type -s T --description 'Optional directive type.'
complete -c nvme-copy -l dir-spec -s S --description 'Optional field for directive specifics.'
complete -c nvme-copy -l format -s F --description 'source range entry format.'

