# nvme-zns-close-zone
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-zns-close-zone.1.gz
complete -c nvme-zns-close-zone -s n -l namespace-id --description 'Use the provided namespace id for the command.'
complete -c nvme-zns-close-zone -s s -l start-lba --description 'The starting LBA of the zone to close.'
complete -c nvme-zns-close-zone -s a -l select-all --description 'Select all zones for this action.'

