# nvme-wdc-namespace-resize
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nvme-wdc-namespace-resize.1.gz
complete -c nvme-wdc-namespace-resize -s n -l namespace-id --description 'Namespace ID; ID of the namespace to resize.'
complete -c nvme-wdc-namespace-resize -s o -l op-option --description 'Overprovisioning Option; defaults to 0xF . sp . if n \\{\\.'

