# od
# Autogenerated from man page /usr/lib/jvm/default/man/man1/od.1p.gz
complete -c od -o Aaddress_base --description 'br Specify the input offset base.  See the EXTENDED DESCRIPTION section.'
complete -c od -o jskip --description 'Jump over R skip bytes from the beginning of the input.'
complete -c od -o Ncount --description 'Format no more than R count bytes of input.'
complete -c od -o ttype_string --description 'br Specify one or more output types.  See the EXTENDED DESCRIPTION section.'
complete -c od -o bcdosx --description 'options is significant.'
complete -c od -o bcdostx --description 'options.'
complete -c od -s n --description 'respectively, for the.'

