# ostree-sign
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ostree-sign.1.gz
complete -c ostree-sign -l verify --description 'Verify signatures.'
complete -c ostree-sign -s s -l sign-type --description 'Use particular signature mechanism.'
complete -c ostree-sign -l keys-file --description 'Read key(s) from file filename.  Valid for ed25519 signature type.'
complete -c ostree-sign -l keys-dir --description 'Redefine the system path, where to search files and subdirectories with well-…'

