# ostree-static-delta
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ostree-static-delta.1.gz
complete -c ostree-static-delta -l from --description '.'
complete -c ostree-static-delta -l to --description '.'
complete -c ostree-static-delta -l empty --description '.'
complete -c ostree-static-delta -l max-usize --description '.'
complete -c ostree-static-delta -l sign-type --description '.'
complete -c ostree-static-delta -l sign --description '.'
complete -c ostree-static-delta -l keys-file --description '.'
complete -c ostree-static-delta -l keys-dir --description '.'

