# ostree-checkout
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ostree-checkout.1.gz
complete -c ostree-checkout -l user-mode -s U --description 'Do not change file ownership or initialize extended attributes.'
complete -c ostree-checkout -l subpath --description 'Checkout sub-directory PATH.'
complete -c ostree-checkout -l union --description 'Keep existing directories and unchanged files, overwrite existing files.'
complete -c ostree-checkout -l union-add --description 'Keep existing directories and files.'
complete -c ostree-checkout -l union-identical --description 'Like --union, but error out if a file would be replaced with a different file.'
complete -c ostree-checkout -l whiteouts --description 'Process whiteout files (Docker style).'
complete -c ostree-checkout -l allow-noent --description 'Do nothing if specified path does not exist.'
complete -c ostree-checkout -l from-stdin --description 'Process many checkouts from standard input.'
complete -c ostree-checkout -l from-file --description 'Process many checkouts from input file.'
complete -c ostree-checkout -l fsync --description 'POLICY is a boolean which specifies whether fsync should be used or not.'
complete -c ostree-checkout -l require-hardlinks -s H --description 'Do not fall back to full copies if hardlinking fails.'
complete -c ostree-checkout -l force-copy-zerosized -s z --description 'This option does nothing; the functionality is now always on by default.'
complete -c ostree-checkout -l force-copy -s C --description 'Never hardlink (but may reflink if available).'
complete -c ostree-checkout -l bareuseronly-dirs -s M --description 'Suppress mode bits outside of 0775 for directories (suid, world writable, etc.'
complete -c ostree-checkout -l skip-list --description 'Skip checking out the absolute file paths listed in FILE, one per line.'
complete -c ostree-checkout -l selinux-policy --description 'Set SELinux labels based on policy in root filesystem PATH (may be /).'

