# outguess
# Autogenerated from man page /usr/man/man1/outguess.1.gz
complete -c outguess -s F -d 'Specifies that OutGuess should preserve statistics based on frequency counts'
complete -c outguess -o kK -d 'Specify the secret key used to encrypt and hide the message in the provided d…'
complete -c outguess -o dD -d 'Specify the filename containing a message to be hidden in the data'
complete -c outguess -o sS -d 'Specify the initial seed the iterator object uses for selecting bits in the r…'
complete -c outguess -o iI -d 'Specify the upper limit for finding an optimal iterator seed'
complete -c outguess -o eE -d 'Use error correction for data encoding and decoding'
complete -c outguess -s r -d 'Retrieve a message from a data object'
complete -c outguess -s x -d 'If the second key does not create an iterator object that is successful in em…'
complete -c outguess -s p -d 'Passes a string as parameter to the destination data handler'
complete -c outguess -s m -d 'Mark pixels that have been modified'
complete -c outguess -s t -d 'Collect statistics about redundant bit usage'
complete -c outguess -s d -d 'hidden. txt monkey. jpg out. jpg'
complete -c outguess -s E -s K -d '"secret2"'
complete -c outguess -s D -d 'hide2. txt monkey. jpg out. jpg'
complete -c outguess -s e -d 'out. jpg message. txt'

