# patch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/patch.1p.gz
complete -c patch -o ddir --description 'Change the current directory to R dir before processing as described in the E…'
complete -c patch -o Ddefine --description 'Mark changes with one of the following C preprocessor constructs: . RS 10  .'
complete -c patch -o ipatchfile --description 'Read the patch information from the file named by the pathname R patchfile , …'
complete -c patch -o ooutfile --description 'Instead of modifying the files (specified by the R file operand or the differ…'
complete -c patch -o rrejectfile --description 'Override the default reject filename.'
complete -c patch -s C --description 'options are specified).'
complete -c patch -s U --description 'options are specified).'
complete -c patch -s w --description 'option in early proposals was changed to.'
complete -c patch -s L --description '.'

