# pidof
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pidof.1.gz
complete -c pidof -s s --description 'Single shot - this instructs the program to only return one pid.'
complete -c pidof -s c --description 'Only return process ids that are running with the same root directory.'
complete -c pidof -s q --description 'Quiet mode, suppress any output and only sets the exit status accordingly.'
complete -c pidof -s w --description 'Show also processes that do not have visible command line (e. g.'
complete -c pidof -s x --description 'Scripts too - this causes the program to also return process id\'s of shells r…'
complete -c pidof -s o --description 'Tells pidof to omit processes with that process id.'
complete -c pidof -s S --description 'Use separator as a separator put between pids.'

