# pip2-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pip2-config.1.gz
complete -c pip2-config -l editor -d 'Editor to use to edit the file'
complete -c pip2-config -l global -d 'Use the system-wide configuration file only'
complete -c pip2-config -l user -d 'Use the user configuration file only'
complete -c pip2-config -l site -d 'Use the current environment configuration file only'

