# pip2-uninstall
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pip2-uninstall.1.gz
complete -c pip2-uninstall -s r -l requirement -d 'Uninstall all the packages listed in the given requirements file'
complete -c pip2-uninstall -s y -l yes -d 'Don\\(aqt ask for confirmation of uninstall deletions'

