# pip2-freeze
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pip2-freeze.1.gz
complete -c pip2-freeze -s r -l requirement -d 'Use the order in the given requirements file and its comments when generating…'
complete -c pip2-freeze -s f -l find-links -d 'URL for finding packages, which will be added to the output'
complete -c pip2-freeze -s l -l local -d 'If in a virtualenv that has global access, do not output globally-installed p…'
complete -c pip2-freeze -l user -d 'Only output packages installed in user-site'
complete -c pip2-freeze -l path -d 'Restrict to the specified installation path for listing packages (can be used…'
complete -c pip2-freeze -l all -d 'Do not skip these packages in the output: distribute, wheel, setuptools, pip2'
complete -c pip2-freeze -l exclude-editable -d 'Exclude editable package from output'
complete -c pip2-freeze -l exclude -d 'Exclude specified package from the output'

