# pip2-list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pip2-list.1.gz
complete -c pip2-list -s o -l outdated -d 'List outdated packages'
complete -c pip2-list -s u -l uptodate -d 'List uptodate packages'
complete -c pip2-list -s e -l editable -d 'List editable projects'
complete -c pip2-list -s l -l local -d 'If in a virtualenv that has global access, do not list globally-installed pac…'
complete -c pip2-list -l user -d 'Only output packages installed in user-site'
complete -c pip2-list -l path -d 'Restrict to the specified installation path for listing packages (can be used…'
complete -c pip2-list -l pre -d 'Include pre-release and development versions'
complete -c pip2-list -l format -d 'Select the output format among: columns (default), freeze, or json'
complete -c pip2-list -l not-required -d 'List packages that are not dependencies of installed packages'
complete -c pip2-list -l exclude-editable -d 'Exclude editable package from output'
complete -c pip2-list -l include-editable -d 'Include editable package from output'
complete -c pip2-list -l exclude -d 'Exclude specified package from the output'

