# pip2-debug
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pip2-debug.1.gz
complete -c pip2-debug -l platform -d 'Only use wheels compatible with <platform>'
complete -c pip2-debug -l python-version -d 'The Python interpreter version to use for wheel and "Requires-Python" compati…'
complete -c pip2-debug -l implementation -d 'Only use wheels compatible with Python implementation <implementation>, e. g'
complete -c pip2-debug -l abi -d 'Only use wheels compatible with Python abi <abi>, e. g.  \\(aqpypy_41\\(aq'

