# ppscheck
# Autogenerated from man page /usr/lib/jvm/default/man/man8/ppscheck.8.gz
complete -c ppscheck -s '?' -s h -l help --description '.'
complete -c ppscheck -s V -l version --description '.'

