# pr
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pr.1p.gz
complete -c pr -o column --description 'Produce multi-column output that is arranged in R column columns (the default…'
complete -c pr -o hheader --description 'Use the string R header to replace the contents of the R file operand in the …'
complete -c pr -o llines --description 'Override the 66-line default and reset the page length to R lines .'
complete -c pr -o ooffset --description 'Each line of output shall be preceded by offset <space> characters.'
complete -c pr -s p --description 'Pause before beginning each page if the standard output is directed to a term…'
complete -c pr -s 2 --description 'a problem when a full page with headers and trailers is produced, it would be…'

