# prs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/prs.1p.gz
complete -c prs -o ddataspec --description 'Specify the output data specification.'
complete -c prs -s r --description 'Specify the SCCS identification string (SID) of a delta for which information…'
complete -c prs -s e --description 'Request information for all deltas created earlier than and including the del…'
complete -c prs -s l --description 'Request information for all deltas created later than and including the delta…'
complete -c prs -o ccutoff --description 'Indicate the R cutoff date-time, in the form: . RS 10  . sp . RS 4 .'
complete -c prs -s d --description 'Specify the output data specification.'
complete -c prs -s c --description 'option.'
complete -c prs -s a --description 'Request writing of information for both removed--that is, delta type =c R (se…'

