# qbittorrent
# Autogenerated from man page /usr/lib/jvm/default/man/man1/qbittorrent.1.gz
complete -c qbittorrent -l help --description '.'
complete -c qbittorrent -l version --description 'number.'
complete -c qbittorrent -l no-splash --description '.'
complete -c qbittorrent -l webui-port --description '8080).'

