# qemu-pr-helper
# Autogenerated from man page /usr/lib/jvm/default/man/man8/qemu-pr-helper.8.gz
complete -c qemu-pr-helper -s d -l daemon --description 'run in the background (and create a PID file).'
complete -c qemu-pr-helper -s q -l quiet --description 'decrease verbosity.'
complete -c qemu-pr-helper -s v -l verbose --description 'increase verbosity.'
complete -c qemu-pr-helper -s f -l pidfile --description 'PID file when running as a daemon.'
complete -c qemu-pr-helper -s k -l socket --description 'path to the socket.'
complete -c qemu-pr-helper -s T -l trace --description 'Specify tracing options. sp [enable=]PATTERN NDENT 7. 0 NDENT 3.'
complete -c qemu-pr-helper -s u -l user --description 'user to drop privileges to.'
complete -c qemu-pr-helper -s g -l group --description 'group to drop privileges to.'
complete -c qemu-pr-helper -s h -l help --description 'Display a help message and exit.'
complete -c qemu-pr-helper -s V -l version --description 'Display version information and exit.'

