# qrls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/qrls.1p.gz
complete -c qrls -o hhold_list --description 'Define the types of holds to be removed from the batch job. RS 10  .'
complete -c qrls -s h --description 'Define the types of holds to be removed from the batch job.  The qrls.'

