# recoverjpeg
# Autogenerated from man page /usr/lib/jvm/default/man/man1/recoverjpeg.1.gz
complete -c recoverjpeg -s h -d 'Display an help message. RS . RE'
complete -c recoverjpeg -s b -d 'Set the size of blocks in bytes'
complete -c recoverjpeg -s d -d 'Set the directory format string (printf-style, default: use the current direc…'
complete -c recoverjpeg -s f -d 'Set the file name format string (printf-style, default: \\[lq]image%05d'
complete -c recoverjpeg -s i -d 'Set the initial index value for image numbering (default: 0). RS . RE'
complete -c recoverjpeg -s m -d 'Maximum size of extract jpeg files'
complete -c recoverjpeg -s o -d 'Change the working directory before restoring files'
complete -c recoverjpeg -s q -d 'Be quiet and do not display anything. RS . RE'
complete -c recoverjpeg -s r -d 'Set the readsize in bytes.  By default, this is 128 MiB'
complete -c recoverjpeg -s s -d 'Set the cutoff size in bytes.  Files smaller than that will be ignored. RS '
complete -c recoverjpeg -s S -d 'Set the number of bytes to skip at the beginning of the filesystem image'
complete -c recoverjpeg -s v -d 'Be verbose and describes the process of jpeg identification'
complete -c recoverjpeg -s V -d 'Display program version and exit'

