# recovermov
# Autogenerated from man page /usr/lib/jvm/default/man/man1/recovermov.1.gz
complete -c recovermov -s h -d 'Display an help message. RS . RE'
complete -c recovermov -s b -d 'Set the size of blocks in bytes'
complete -c recovermov -s i -d 'Set the initial index value for image numbering (default: 0). RS . RE'
complete -c recovermov -s n -d 'Basename to use to create the salvaged files.  Default is \\f[C]video_\\f[]'
complete -c recovermov -s o -d 'Change the working directory before restoring files'
complete -c recovermov -s V -d 'Display program version and exit'

