# remove-duplicates
# Autogenerated from man page /usr/lib/jvm/default/man/man1/remove-duplicates.1.gz
complete -c remove-duplicates -s f -d 'If -f is not given, duplicate will be identified twice (once in every directi…'

