# rifiuti
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rifiuti.1.gz
complete -c rifiuti -s o -l output -d 'Write output to FILE'
complete -c rifiuti -s x -l xml -d 'Output in XML format instead of tab-delimited values'
complete -c rifiuti -s l -l legacy-filename -d 'Show legacy filename if available (like \\(lq\\fCD:\\\\Progra~1\\\\\\(rq), and speci…'
complete -c rifiuti -s z -l localtime -d 'Present deletion time in numeric time zone of local system running the program'
complete -c rifiuti -s t -l delimiter -d 'String to use as delimiter (TAB by default)'
complete -c rifiuti -s n -l no-heading -d 'Don\'t show recycle bin path name, metadata and field headers'
complete -c rifiuti -s 8 -l always-utf8 -d '(Option deprecated since 0. 7. 0 version) . PP  . SS MISCELLANEOUS OPTIONS'
complete -c rifiuti -s v -l version -d 'Print version information and exit'
complete -c rifiuti -s h -l help -d 'Show help options and exit'
complete -c rifiuti -l help-all -d 'Show all help options and exit'
complete -c rifiuti -l help-text -d 'Show plain text output options and exit.  EXAMPLES'

