# rndc-confgen
# Autogenerated from man page /usr/lib/jvm/default/man/man8/rndc-confgen.8.gz
complete -c rndc-confgen -s a -d 'Do automatic rndc configuration.  This creates a file rndc'
complete -c rndc-confgen -s A -d 'Specifies the algorithm to use for the TSIG key'
complete -c rndc-confgen -s b -d 'Specifies the size of the authentication key in bits'
complete -c rndc-confgen -s c -d 'Used with the -a option to specify an alternate location for rndc. key'
complete -c rndc-confgen -s h -d 'Prints a short summary of the options and arguments to rndc-confgen'
complete -c rndc-confgen -s k -d 'Specifies the key name of the rndc authentication key'
complete -c rndc-confgen -s p -d 'Specifies the command channel port where named listens for connections from r…'
complete -c rndc-confgen -s s -d 'Specifies the IP address where named listens for command channel connections …'
complete -c rndc-confgen -s t -d 'Used with the -a option to specify a directory where named will run chrooted'
complete -c rndc-confgen -s u -d 'Used with the -a option to set the owner of the rndc. key file generated'

