# rndc
# Autogenerated from man page /usr/lib/jvm/default/man/man8/rndc.8.gz
complete -c rndc -s 4 -d 'Use IPv4 only'
complete -c rndc -s 6 -d 'Use IPv6 only'
complete -c rndc -s b -d 'Use source-address as the source address for the connection to the server'
complete -c rndc -s c -d 'Use config-file as the configuration file instead of the default, /etc/rndc'
complete -c rndc -s k -d 'Use key-file as the key file instead of the default, /etc/rndc. key'
complete -c rndc -s s -d 'server is the name or address of the server which matches a server statement …'
complete -c rndc -s p -d 'Send commands to TCP port port instead of BIND 9\\(aqs default control channel…'
complete -c rndc -s q -d 'Quiet mode: Message text returned by the server will not be printed except wh…'
complete -c rndc -s r -d 'Instructs rndc to print the result code returned by named after executing the…'
complete -c rndc -s V -d 'Enable verbose logging'
complete -c rndc -s y -d 'Use the key key_id from the configuration file'
complete -c rndc -s d -s f
complete -c rndc -o redirect -d 'would specify a zone called "-redirect". ) LIMITATIONS'

