# setcifsacl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/setcifsacl.1.gz
complete -c setcifsacl -s h -d 'Print usage message and exit'
complete -c setcifsacl -s v -d 'Print version number and exit'
complete -c setcifsacl -s a -d 'Add one or more ACEs to an ACL of a security descriptor'
complete -c setcifsacl -s D -d 'Delete one or more ACEs from an ACL of a security descriptor'
complete -c setcifsacl -s M -d 'Modify one or more ACEs from an ACL of a security descriptor'
complete -c setcifsacl -s S -d 'Set an ACL of security descriptor with the list of ACEs Existing ACL is repla…'

