# siege
# Autogenerated from man page /usr/lib/jvm/default/man/man1/siege.1.gz
complete -c siege -s V -l version -d 'Displays the \\f(CWsiege release version and copyright information'
complete -c siege -s h -l help -d 'Prints a help message describing \\f(CWsiege\'s command-line options'
complete -c siege -s C -l config -d 'Prints a detailed summary of all the currently configured options, most of wh…'
complete -c siege -s v -l verbose -d 'This directive puts \\f(CWsiege into verbose mode which is actually a  default…'
complete -c siege -s q -l quiet -d 'This directive silences \\f(CWsiege'
complete -c siege -s g -l get -d 'This option allows you to request a \\s-1URL\\s0 and watch the header  transact…'
complete -c siege -s p -l print -d 'This option is similar to -g / --get but it \\s-1PRINTS\\s0 the page it receive…'
complete -c siege -s c -l concurrent -d 'This option allows you to set the concurrent number of users'
complete -c siege -s r -l reps -d 'This option tells each siege user how many times it should run'
complete -c siege -s t -l time -d 'This option is similar to --reps but instead of specifying the number  of tim…'
complete -c siege -s d -l delay -d 'This option instructs \\f(CWsiege how long to delay between each page  request'
complete -c siege -s b -l benchmark -d 'This directive tells siege to go into benchmark mode'
complete -c siege -s i -l internet -d 'This option sets siege into what we call internet mode'
complete -c siege -s f -l file -d 'This option tells siege to work with a list of urls inside a text  file'
complete -c siege -s R -l rc -d 'This directive allows you to set an alternative resource file'
complete -c siege -s L -l log -d 'The default log file is \\f(CW$prefix/var/log/siege. log'
complete -c siege -s m -l mark -d el
complete -c siege -s H -l header -d el
complete -c siege -s A -l agent -d el
complete -c siege -s T -l content-type -d el
complete -c siege -l no-parser -d 'Turn off the \\s-1HTML\\s0 parser'

