# sort
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sort.1p.gz
complete -c sort -o ooutput --description 'Specify the name of an output file to be used instead of the standard output.'
complete -c sort -o tchar --description 'Use R char as the field separator character; R char shall not be considered t…'
complete -c sort -o um --description 'with one input file keep the first in each set of lines with equal keys.'
complete -c sort -s y --description 'option was omitted because of non-portability.  The.'

