# split
# Autogenerated from man page /usr/lib/jvm/default/man/man1/split.1p.gz
complete -c split -o asuffix_length --description 'br Use R suffix_length letters to form the suffix portion of the filenames of…'
complete -c split -o bn --description 'Split a file into pieces R n bytes in size.'
complete -c split -o bnk --description 'Split a file into pieces R n *1\\|024 bytes in size.'
complete -c split -o bnm --description 'Split a file into pieces R n *1\\|048\\|576 bytes in size.'

