# squashfuse
# Autogenerated from man page /usr/lib/jvm/default/man/man1/squashfuse.1.gz
complete -c squashfuse -s V --description 'show FUSE version.'
complete -c squashfuse -s h --description 'print help.'
complete -c squashfuse -s d --description 'enable debug output (implies f ).'
complete -c squashfuse -s f --description 'foreground operation.'
complete -c squashfuse -s o --description 'allow access by other users.'

