# sshmitm
# Autogenerated from man page /usr/lib/jvm/default/man/man8/sshmitm.8.gz
complete -c sshmitm -s d -d 'Enable verbose debugging output'
complete -c sshmitm -s I -d 'Monitor / hijack an interactive session'
complete -c sshmitm -s p -d 'Specify the local port to listen on'

