# sshow
# Autogenerated from man page /usr/lib/jvm/default/man/man8/sshow.8.gz
complete -c sshow -s d -d 'Enable verbose debugging output'
complete -c sshow -s i -d 'Specify the interface to listen on'
complete -c sshow -s p -d 'Process packets from the specified PCAP capture file instead of the network'

