# systemd-dissect
# Autogenerated from man page /usr/lib/jvm/default/man/man1/systemd-dissect.1.gz
complete -c systemd-dissect -l read-only -s r --description 'Operate in read-only mode.'
complete -c systemd-dissect -l fsck --description 'Turn off automatic file system checking.'
complete -c systemd-dissect -l mkdir --description 'If combined with --mount the directory to mount the OS image to is created if…'
complete -c systemd-dissect -l discard --description 'Takes one of "disabled", "loop", "all", "crypto".'
complete -c systemd-dissect -l root-hash -l root-hash-sig -l verity-data --description 'Configure various aspects of Verity data integrity for the OS image.'
complete -c systemd-dissect -l image --description 'switch, and be used as root file system for system service using the RootImag…'
complete -c systemd-dissect -l mount -s m --description '.'
complete -c systemd-dissect -s R --description 'switch (for recursive operation), so that the OS image and all nested partiti…'
complete -c systemd-dissect -s M --description '.'
complete -c systemd-dissect -l copy-from -s x --description '.'
complete -c systemd-dissect -l copy-to -s a --description '.'
complete -c systemd-dissect -l json --description '.'
complete -c systemd-dissect -s h -l help --description '.'
complete -c systemd-dissect -l version --description '.'
complete -c systemd-dissect -l add --description 'fsck(8) command, in automatic fixing mode.'

