# t50
# Autogenerated from man page /usr/lib/jvm/default/man/man8/t50.8.gz
complete -c t50 -l flood -d 'Also, to avoid this error you can provide the host address as the first argum…'
complete -c t50 -l threshold -d 'Number of packets to inject (default 1000)'
complete -c t50 -s B -l bogus-csum -d 'Use a bogus "random " checksum instead of calculating the actual packet check…'
complete -c t50 -l turbo -d 'Inject packets faster (creates a child process)'
complete -c t50 -l shuffle -d 'When used with T50 "protocol", it will shuffle the available protocols'
complete -c t50 -s s -l saddr -d 'IP header source address (default RANDOM)'
complete -c t50 -s p -l protocol -d 'Select an specific protocol to use (default: TCP'
complete -c t50 -s h -l help -d 'Display all available options and their defaults'
complete -c t50 -s v -l version -d 'Display t50 version'
complete -c t50 -s l -l list-protocols -d 'Lists all available protocols T50 can provide'

