# tail
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tail.1p.gz
complete -c tail -o cnumber --description 'The application shall ensure that the R number option-argument is a decimal i…'
complete -c tail -o @Relative --description 'none@Relative to the end of the file.'
complete -c tail -s 1 --description '.'
complete -c tail -s b --description 'option was omitted because of the general non-portability of block-sized unit…'

