# tcpkill
# Autogenerated from man page /usr/lib/jvm/default/man/man8/tcpkill.8.gz
complete -c tcpkill -s i -d 'Specify the interface to listen on'
complete -c tcpkill -o '1...9' -d 'Specify the degree of brute force to use in killing a connection'

