# tcpnice
# Autogenerated from man page /usr/lib/jvm/default/man/man8/tcpnice.8.gz
complete -c tcpnice -s A -d 'Inject TCP tiny window advertisements'
complete -c tcpnice -s I -d 'Inject ICMP source quench replies'
complete -c tcpnice -s M -d 'Inject ICMP fragmentation-needed replies with tiny next-hop MTUs'
complete -c tcpnice -s i -d 'Specify the interface to listen on'

