# tcpxtract
# Autogenerated from man page /usr/man/man1/tcpxtract.1.gz
complete -c tcpxtract -l file -s f -d 'to specify an input capture file instead of a device'
complete -c tcpxtract -l device -s d -d 'to specify an input device (i. e.  eth0)'
complete -c tcpxtract -l config -s c -d 'use FILE as the config file'
complete -c tcpxtract -l output -s o -d 'dump files to DIRECTORY instead of current directory'
complete -c tcpxtract -l version -s v -d 'display the version number of this program'
complete -c tcpxtract -l help -s h -d 'display this lovely screen SEE ALSO The full documentation for tcpxtract is m…'

