# testasciidoc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/testasciidoc.1.gz
complete -c testasciidoc -s f -l conf-file --description 'Use configuration file CONF_FILE for more information about the configuration…'
complete -c testasciidoc -l force --description 'Update all test data overwriting existing data.'

