# tiff2rgba
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tiff2rgba.1.gz
complete -c tiff2rgba -s c --description 'Specify a compression scheme to use when writing image data:  "-c none" for n…'
complete -c tiff2rgba -s r --description 'Write data with a specified number of rows per strip; by default the number o…'
complete -c tiff2rgba -s b --description 'Process the image one block (strip/tile) at a time instead of by reading the …'
complete -c tiff2rgba -s n --description 'Drop the alpha component from the output file, producing a pure RGB file.'
complete -c tiff2rgba -s M --description 'Set maximum memory allocation size (in MiB).  The default is 256MiB.'

