# touch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/touch.1p.gz
complete -c touch -o ddate_time --description 'Use the specified R date_time instead of the current time.'
complete -c touch -o rref_file --description 'Use the corresponding time of the file named by the pathname R ref_file inste…'
complete -c touch -o ttime --description 'Use the specified R time instead of the current time.'

