# tracker3-reset
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker3-reset.1.gz
complete -c tracker3-reset -s s -l filesystem --description 'Removes data stored by tracker-miner-fs(1).'
complete -c tracker3-reset -s r -l rss --description 'Removes data stored by tracker-miner-rss(1).'
complete -c tracker3-reset -s f -l file --description 'Resets all indexed information about FILE, works recursively for directories.'

