# tracker3-tag
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker3-tag.1.gz
complete -c tracker3-tag -s t -l list --description 'List all tags.'
complete -c tracker3-tag -s s -l show-files --description 'Show the files associated with each tag.'
complete -c tracker3-tag -s a -l add --description 'Add a tag with the name TAG.'
complete -c tracker3-tag -s d -l delete --description 'Delete a tag with the name TAG.'
complete -c tracker3-tag -s e -l description --description 'This option ONLY applies when using --add and provides a description to go wi…'
complete -c tracker3-tag -s l -l limit --description 'Limit search to N results.  The default is 512.'
complete -c tracker3-tag -s o -l offset --description 'Offset the search results by N.'
complete -c tracker3-tag -s r -l and-operator --description 'Use AND operator for search terms instead of OR (the default).  For example:.'

