# tracker3-info
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker3-info.1.gz
complete -c tracker3-info -s f -l full-namespaces --description 'By default, all keys and values reported about any given file are returned in…'
complete -c tracker3-info -s c -l plain-text-content --description 'If the resource being displayed has nie:PlainTextContent (i. e.'
complete -c tracker3-info -s i -l resource-is-iri --description 'In most cases, the file argument supplied points to a URL or PATH which is qu…'
complete -c tracker3-info -s t -l turtle --description 'Output results as Turtle RDF.'

