# tracker-miner-fs-3
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker-miner-fs-3.1.gz
complete -c tracker-miner-fs-3 -s '?' -l help --description 'Show summary of options.'
complete -c tracker-miner-fs-3 -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-miner-fs-3 -s s -l initial-sleep --description 'Sets the initial sleep time before crawling the file system is started.'
complete -c tracker-miner-fs-3 -s n -l no-daemon --description 'Tells the miner to exit once all indexing has finished and the database is up…'
complete -c tracker-miner-fs-3 -s e -l eligible --description 'Checks if FILE is eligible for being mined based on the current configuration…'

