# tracker3-extract
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker3-extract.1.gz
complete -c tracker3-extract -s o -l output-format --description 'Choose which format to use to output results.'

