# tracker3-daemon
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tracker3-daemon.1.gz
complete -c tracker3-daemon -s p -l list-processes --description 'This lists all Tracker processes in the system.'
complete -c tracker3-daemon -l kill --description 'This uses SIGKILL to stop all Tracker processes found matching the parameter,…'
complete -c tracker3-daemon -l terminate --description 'This uses SIGTERM to stop all Tracker processes.'
complete -c tracker3-daemon -s s -l start --description 'Starts all miners.'
complete -c tracker3-daemon -s f -l follow --description 'Follow status changes to daemons as they happen.'
complete -c tracker3-daemon -s w -l watch --description 'Watch changes that happen to the database in real time.'
complete -c tracker3-daemon -l list-common-statuses --description 'This will list statuses most commonly produced by miners and the store.'
complete -c tracker3-daemon -l list-miners-running --description 'This will list all miners which have responded to a D-Bus call.'
complete -c tracker3-daemon -l list-miners-available --description 'This will list all miners which are available even if they are not running at…'
complete -c tracker3-daemon -l pause-details --description 'For listing all miners which are paused and the reasons for being paused, you…'
complete -c tracker3-daemon -l miner --description 'This argument is used with --pause or --resume to say which miner you want to…'
complete -c tracker3-daemon -l pause --description 'The reason here is useful to know WHY the miner should be paused.'
complete -c tracker3-daemon -l pause-for-process --description 'This works exactly the same way as --pause with the exception that it only ke…'
complete -c tracker3-daemon -l resume --description 'The cookie is given by a successful --pause command.'

