# u3-tool
# Autogenerated from man page /usr/lib/jvm/default/man/man1/u3-tool.1.gz
complete -c u3-tool -s c -d 'Change current password'
complete -c u3-tool -s d -d 'Disable device security leaving the data intact'
complete -c u3-tool -s D -d 'Dump all raw info(for debug)'
complete -c u3-tool -s e -d 'Enable device security, protecting all files currently on the data partition …'
complete -c u3-tool -s h -d 'Print a short help message'
complete -c u3-tool -s i -d 'Display device information'
complete -c u3-tool -s l -d 'Load a new CD image into the cd partition of the device'
complete -c u3-tool -s p -d 'Repartition device, reassinging the device space between the cd and data part…'
complete -c u3-tool -s R -d 'Reset device security destroying private data'
complete -c u3-tool -s u -d 'Unlock secured data partition.  This requires the current password'
complete -c u3-tool -s v -d 'Use verbose output'
complete -c u3-tool -s V -d 'Print version information'

