# urlsnarf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/urlsnarf.8.gz
complete -c urlsnarf -s n -d 'Do not resolve IP addresses to hostnames'
complete -c urlsnarf -s i -d 'Specify the interface to listen on'
complete -c urlsnarf -s p -d 'Process packets from the specified PCAP capture file instead of the network'
complete -c urlsnarf -s v -d '"Versus" mode.  Invert the sense of matching, to select non-matching URLs'

