# uustat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/uustat.1p.gz
complete -c uustat -s q --description 'Write the jobs queued for each machine.'
complete -c uustat -o kjobid --description 'Kill the R uucp request whose job identification is R jobid .'
complete -c uustat -o rjobid --description 'Rejuvenate R jobid .'
complete -c uustat -o ssystem --description 'Write the status of all R uucp requests for remote system R system .'
complete -c uustat -s k --description 'Kill the uucp request whose job identification is jobid .'
complete -c uustat -s r --description 'Rejuvenate jobid .'
complete -c uustat -s s --description 'Write the status of all uucp requests for remote system system .'
complete -c uustat -s u --description 'Write the status of all uucp requests issued by user .  OPERANDS None.'

