# vmware
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vmware.1.gz
complete -c vmware -s s -d 'Set the configuration variable \\fIname\\fP to \\fIvalue\\fP, overriding other de…'
complete -c vmware -s n -d 'Open a new window'
complete -c vmware -s t -d 'Open a virtual machine or team in a new tab in an existing window'
complete -c vmware -s x -d 'Power on the virtual machine on startup'
complete -c vmware -s X -d 'Power on and switch to full screen mode'
complete -c vmware -s q -d 'Attempt to exit the virtual machine after powering off'
complete -c vmware -s v -d 'Display the program version and exit without starting a virtual machine'
complete -c vmware -s W -d 'Starts a second instance of Workstation in a different X server'

