# wapiti-getcookie
# Autogenerated from man page /usr/lib/jvm/default/man/man1/wapiti-getcookie.1.gz
complete -c wapiti-getcookie -s p -l proxy -d 'The given URL will be used as a proxy for HTTP and HTTPS requests'
complete -c wapiti-getcookie -l tor -d 'Make Wapiti use a Tor listener (same as --proxy socks://127. 0. 0. 1:9050/)'
complete -c wapiti-getcookie -s a -l auth-cred -d 'Set credentials to use for HTTP authentication on the target'
complete -c wapiti-getcookie -l auth-type -d 'Set the authentication mechanism to use'
complete -c wapiti-getcookie -s H -l header -d 'Set a custom HTTM header to inject in every request sent by Wapiti'
complete -c wapiti-getcookie -s A -l user-agent -d 'Default behavior of Wapiti is to use the same User-Agent as the TorBrowser, m…'
complete -c wapiti-getcookie -s d -l data -d 'wapiti-getcookie will parse forms and ask your input for each field found'

