# wapiti
# Autogenerated from man page /usr/lib/jvm/default/man/man1/wapiti.1.gz
complete -c wapiti -s u
complete -c wapiti -l scope
complete -c wapiti -s m
complete -c wapiti -l list-modules
complete -c wapiti -s l
complete -c wapiti -s p
complete -c wapiti -s a
complete -c wapiti -l auth-type
complete -c wapiti -s c
complete -c wapiti -l skip-crawl
complete -c wapiti -l resume-crawl
complete -c wapiti -l flush-attacks
complete -c wapiti -l flush-session
complete -c wapiti -s s
complete -c wapiti -s x
complete -c wapiti -s r
complete -c wapiti -l skip
complete -c wapiti -s d
complete -c wapiti -l max-links-per-page
complete -c wapiti -l max-files-per-dir
complete -c wapiti -l max-scan-time
complete -c wapiti -l max-parameters
complete -c wapiti -s S -l scan-force
complete -c wapiti -s t
complete -c wapiti -s H
complete -c wapiti -s A
complete -c wapiti -l verify-ssl
complete -c wapiti -l color
complete -c wapiti -s v
complete -c wapiti -s f
complete -c wapiti -s o
complete -c wapiti -l no-bugreport
complete -c wapiti -l version
complete -c wapiti -s h
complete -c wapiti -l url -d 'The URL that will be used as the base for the scan'
complete -c wapiti -l module -d 'Set the list of attack modules (modules names separated with commas) to launc…'
complete -c wapiti -l level -d 'In previous versions Wapiti used to inject attack payloads in query strings e…'
complete -c wapiti -l proxy -d 'The given URL will be used as a proxy for HTTP and HTTPS requests'
complete -c wapiti -l tor -d 'Make Wapiti use a Tor listener (same as --proxy socks://127. 0. 0. 1:9050/)'
complete -c wapiti -l auth-cred -d 'Set credentials to use for HTTP authentication on the target'
complete -c wapiti -l cookie -d 'Load cookies from a Wapiti JSON cookie file'
complete -c wapiti -l store-session
complete -c wapiti -l start -d 'If for some reasons, Wapiti doesn\'t find any (or enough) URLs from the base U…'
complete -c wapiti -l exclude -d 'Prevent the given URL from being scanned'
complete -c wapiti -l remove -d 'If the given parameter is found in scanned URL it will be automatically remov…'
complete -c wapiti -l depth -d 'When Wapiti crawls a website it gives each found URL a depth value'
complete -c wapiti -l endpoint -d 'For example the SSRF module inject the endpoint URL into webpage arguments to…'
complete -c wapiti -l internal-endpoint -d 'The internal endpoint is used by Wapiti to fetch results of attacks'
complete -c wapiti -l external-endpoint -d 'Using your own endpoint may reduce risk of being caught by NIDS or WAF'
complete -c wapiti -l timemout -d 'Time to wait (in seconds) for a HTTP response before considering failure'
complete -c wapiti -l header -d 'Set a custom HTTM header to inject in every request sent by Wapiti'
complete -c wapiti -l user-agent -d 'Default behavior of Wapiti is to use the same User-Agent as the TorBrowser, m…'
complete -c wapiti -l verbose -d 'Set the level of verbosity for the output'
complete -c wapiti -l format -d 'Set the format of the report'
complete -c wapiti -l output -d 'Set the path were the report will be generated'
complete -c wapiti -l help -d 'Show detailed options description'

