# webspy
# Autogenerated from man page /usr/lib/jvm/default/man/man8/webspy.8.gz
complete -c webspy -s i -d 'Specify the interface to listen on'
complete -c webspy -s p -d 'Process packets from the specified PCAP capture file instead of the network'

