# xgps
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xgps.1.gz
complete -c xgps -s '?' -s h -l help --description '.'
complete -c xgps -o device --description '.'
complete -c xgps -s D -l debug --description '.'
complete -c xgps -l host --description '.'
complete -c xgps -s p -l port --description '.'
complete -c xgps -s V -l version --description '.'
complete -c xgps -s l -l llfmt --description '.'
complete -c xgps -s r -l rotate --description '.'
complete -c xgps -s u -l units --description 'option.'
complete -c xgps -l nautical --description 'option forces this mode.  The.'
complete -c xgps -l landspeed --description 'option produces a simple speedometer.'
complete -c xgps -l speedunits --description 'option can be used to set the speed units for display; follow the keyword wit…'
complete -c xgps -l maxspeed --description 'sets the maximum on the speedometer.  ENVIRONMENT.'

